import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;
public class addemp extends javax.swing.JFrame {

    /**
     * Creates new form addemp
     */
    public addemp() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        eno = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        sal = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        dsg = new javax.swing.JComboBox();
        dpt = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ADD EMPLOYEE DETAILS");

        jLabel2.setText("EMPLOYEE NO.");

        jLabel3.setText("EMPLOYEE NAME");

        jLabel4.setText("DESINGNATION");

        jLabel5.setText("SALARY");

        jLabel6.setText("DEPARTMENT");

        eno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enoKeyPressed(evt);
            }
        });

        name.setEnabled(false);

        sal.setEnabled(false);
        sal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salKeyPressed(evt);
            }
        });

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        exit.setText("BACK");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        dsg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CEO", "MANAGER", "FINANCER", "SALES MANAGER", "H.R.", "H.O.D." }));
        dsg.setEnabled(false);

        dpt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CEO", "MANAGING", "FINANCING", "SALES", "H.R'S", "H.O.D'S" }));
        dpt.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(add)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(exit)
                            .addComponent(eno)
                            .addComponent(name)
                            .addComponent(sal)
                            .addComponent(dsg, 0, 139, Short.MAX_VALUE)
                            .addComponent(dpt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(exit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(error)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       if(eno.getText().equals("") || name.getText().equals("") || sal.getText().equals(""))
        {
            //pass.setEnabled(false);
            eno.grabFocus();
            JOptionPane.showMessageDialog(this,"fields cannot be empty");
            
        }
        else
       {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            int en=Integer.parseInt(eno.getText());
            int s=Integer.parseInt(sal.getText());
            
            PreparedStatement ps=con.prepareStatement("Insert into emp values(?,?,?,?,?)");
            ps.setInt(1,en);
            ps.setString(2,name.getText());
           ps.setString(3,(String)dsg.getSelectedItem());
            ps.setInt(4,s);
            ps.setString(5,(String)dpt.getSelectedItem());
           int rs=ps.executeUpdate();
          
           if(rs>0)
           {
                JOptionPane.showMessageDialog(this,"RECORD ADDED");
                name.setEnabled(false);
                sal.setEnabled(false);
                dsg.setEnabled(false);
                dpt.setEnabled(false);
                
                 eno.setText(" ");
                 name.setText(" ");
                 sal.setText(" ");
                
           }
           else
           {
                JOptionPane.showMessageDialog(this,"Not added");   
           }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"duplicate record");
            name.setEnabled(false);
            sal.setEnabled(false);
            dsg.setEnabled(false);
            dpt.setEnabled(false);
                
                 eno.setText(" ");
                 name.setText(" ");
                 sal.setText(" ");
                
        }
      
       } 
    }//GEN-LAST:event_addActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        new emp_man().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void enoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enoKeyPressed
        if((evt.getKeyChar()>='0' && evt.getKeyChar()<='9') || (evt.getKeyChar() == evt.VK_DELETE))
            
        {
           name.setEnabled(true);
           dsg.setEnabled(true);
            dpt.setEnabled(true);
           sal.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Insert integer value");
            eno.setText("");
            name.setEnabled(false);}
    }//GEN-LAST:event_enoKeyPressed

    private void salKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salKeyPressed
         char c=evt.getKeyChar();
      if(!((c>='0') && (c<='9') || (c==evt.VK_BACK_SPACE) || (c==evt.VK_DELETE)))
      {
          JOptionPane.showMessageDialog(this,"ENTER INTEGER VALUE");
          //eno.grabFocus();
          sal.setText("");
      }
    }//GEN-LAST:event_salKeyPressed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addemp().setVisible(true);
            }
        });
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JComboBox dpt;
    private javax.swing.JComboBox dsg;
    private javax.swing.JTextField eno;
    private javax.swing.JLabel error;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name;
    private javax.swing.JTextField sal;
    // End of variables declaration//GEN-END:variables
}
